services:
  cosmosdb:
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "8081:8081"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    volumes:
      - ./_run/cosmosdb:/var/lib/cosmosdb
    networks:
      - localtest
  
  # api:
  #   container_name: api
  #   build: .
  #   ports:
  #     - "7071:7071"
  #   depends_on:
  #     - cosmosdb
  #   environment:
  #     - AzureWebJobsStorage=UseDevelopmentStorage=true
  #     - CosmosDB__Endpoint=http://cosmosdb:8081
  #     - CosmosDB__Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqKZBKg== # Emulator key
  #     - CosmosDB__Database=KitamerakiTestDb
  #   networks:
  #     - localtest

networks:
  localtest:
    driver: bridge